# following line is key to prevent an endless build/deploy cycle
# when travis commits to pages:
  #
if: commit_message !~ ^Deploy.*
dist: xenial
env:
  global:
  - PERL5LIB=/usr/share/perl5
language: python
services:
  - docker
python:
  - '2.7'
branches:
  only:
    - master
before_install:
  - docker pull maj1/icdc:icdc-model-tool-app
install:
  - pip install -r val/reqs.txt
script:
  - pushd val
  - pytest
  - popd
  - pushd mdf
  # run prebuilt model-tool
  - docker run --rm -it -v "$PWD":/opns/wrk  maj1/icdc:icdc-model-tool-app -g wrk/update-model.svg wrk/*.yml
  - cp *.yml ../docs/mdf
  - sed -ie '1,6d' update-model.svg
  - cp update-model.svg ../docs/mdf/ctn-model.svg
  - rm -f update-model.*
  - popd
  - pushd docs
  - cp ./README.md.content ./README.md
  - echo "<div id='graph' style='display:off;'>" >> ./README.md
  - cat ./mdf/ctn-model.svg >> ./README.md
  - echo "</div>" >> ./README.md
  - popd
  - rm -rf __pycache__
  - rm -f MDFValidate/*.pyc

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: true
  verbose: true
  on:
    branch: master
